# Generated by Django 3.1.4 on 2021-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0002_auto_20210205_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcd',
            name='status',
            field=models.CharField(default='off', max_length=4),
        ),
    ]
