# Generated by Django 3.1.4 on 2021-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0003_auto_20210205_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcd',
            name='status',
        ),
    ]
