# Generated by Django 3.1.4 on 2021-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0004_remove_abcd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcd',
            name='status',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
