# Generated by Django 3.1.4 on 2021-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0005_abcd_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=255)),
                ('Status', models.CharField(default='false', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='abcd',
        ),
    ]
