# Generated by Django 3.1.4 on 2021-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0006_auto_20210207_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='None', max_length=50)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('Password', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='User_Id',
            field=models.IntegerField(default=0),
        ),
    ]
