# Generated by Django 3.1.4 on 2021-02-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0007_auto_20210211_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Persons',
        ),
    ]
