# Generated by Django 3.1.4 on 2021-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0008_auto_20210212_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='User',
        ),
    ]
