# Generated by Django 3.1.4 on 2021-02-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0009_auto_20210212_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='User_Id',
            new_name='Userid',
        ),
    ]
