# Generated by Django 3.1.4 on 2021-02-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoWeb', '0010_auto_20210212_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TokenVlaue', models.CharField(max_length=255)),
                ('TokenExpiryDate', models.IntegerField(default=0)),
                ('Status', models.CharField(default='false', max_length=10)),
            ],
        ),
    ]
