# Generated by Django 3.2.5 on 2021-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=225)),
                ('user_email', models.EmailField(max_length=225)),
                ('user_password', models.CharField(max_length=225)),
            ],
        ),
    ]
