# Generated by Django 3.2.5 on 2021-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('todo_content', models.CharField(max_length=500)),
                ('todo_status', models.BooleanField(default=False)),
            ],
        ),
    ]
