# Generated by Django 3.2.5 on 2021-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_usertodos_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodos',
            name='todo_status',
            field=models.BooleanField(default=True),
        ),
    ]
